// Linkawy site copy — AR is from linkawy.io (Oct 2026); EN is a faithful translation for the English version.
window.LK_IMG = 'https://www.linkawy.io/wp-content/themes/linkawy/assets/images/';
window.LK_CONTENT = {
  ar: {
    nav: { home: 'الرئيسية', services: 'خدماتنا', blog: 'المدونة', resources: 'الموارد', learn: 'تعلم السيو', quote: 'اطلب عرض سعر', lang: 'English',
      serviceItems: ['التسويق الالكتروني', 'تحسين محركات البحث (SEO)', 'SEO الذكاء الإصطناعي (GEO)', 'تصميم متجر إلكتروني', 'خدمات الباك لينك', 'خدمة كتابة المحتوى'] },
    hero: { label: 'نهيّئ متجرك لإجابات ChatGPT و Gemini', badge: 'جديد', pre: 'أفضل شركة سيو ', accent: 'للمتاجر الإلكترونية', post: ' والشركات',
      sub: 'اختيارك شركة سيو مناسبة لا يعني تحسين الترتيب فقط، بل بناء قناة نمو تربط محركات البحث بالمبيعات. نقدم استراتيجيات سيو تساعدك على تصدر النتائج وجذب زيارات مؤهلة تتحول إلى إيرادات مستدامة.',
      primary: 'اكتشف الخدمات', secondary: 'كيف نعمل؟', clients: 'عملاء تشرفنا بمعاونتهم:',
      platforms: [['google', 'Result #1', 'Google SERP'], ['gemini', 'AI Overview', 'Gemini'], ['chatgpt', 'LLMO / GEO', 'ChatGPT'], ['semrush', 'DR 80 +3', 'Authority Score'], ['googlemaps', 'Maps ranking', 'Local SEO'], ['applenews', 'Media coverage', 'Digital PR']],
      platformsTitle: 'شركة سيو رائدة في تحويل الزيارات إلى أرباح حقيقية عبر مختلف المنصات' },
    services: { eyebrow: 'خدماتنا', title: 'خدمات السيو التي نقدمها', hl: 'السيو',
      sub: 'استكشف استراتيجياتنا المخصصة التي تقدم التوجيه والدعم لمساعدتك على تصدر نتائج البحث وتحقيق النمو المستدام بثقة.', cta: 'أطلب استشارة مجانية',
      items: [
        ['ShoppingBag', 'سيو شوبيفاي', 'Shopify SEO', 'نحسن الصفحات والمنتجات وبنية المحتوى في متجر شوبيفاي لرفع فرص الظهور وزيادة الزيارات المستهدفة.'],
        ['Store', 'سيو سلة', 'Salla SEO', 'تحسين الصفحات والأقسام والمنتجات والمحتوى الداخلي لمتاجر سلة لزيادة الزيارات العضوية والمبيعات.'],
        ['FileText', 'السيو الداخلي', 'On-Page SEO', 'العناوين والمحتوى والروابط الداخلية وهيكلة الصفحات، حتى تفهم محركات البحث صفحاتك بشكل أفضل.'],
        ['Link', 'السيو الخارجي', 'Off-Page SEO', 'روابط خلفية عالية الجودة من مواقع موثوقة وذات صلة ترفع موثوقية موقعك وترتيبه.'],
        ['ScanSearch', 'فحص مشاكل الموقع', 'SEO Audits', 'تدقيق شامل يكشف المشكلات التقنية ومشاكل السرعة والفهرسة والمحتوى، مع توصيات عملية.'],
        ['Lightbulb', 'استشارات SEO', 'SEO Consulting', 'رؤية واضحة وأولويات محددة تناسب مرحلة نمو مشروعك، سواء بدأت من الصفر أو تطوّر نتائجك.'],
        ['Code', 'السيو التقني', 'Technical SEO', 'سرعة الموقع وتجربة الجوال والأمان وبنية الروابط لضمان سهولة الزحف والفهرسة.'],
        ['Sparkles', 'سيو الذكاء الإصطناعي', 'GEO', 'محتوى واضح وموثوق ومنظم يسهل اقتباسه في محركات الإجابة وتجارب البحث بالذكاء الاصطناعي.']] },
    proof: { pre: 'في المتوسط ساعدنا عملاءنا في زيادة المبيعات العضوية لأكثر من ', num: '270%', post: ' عن طريق الزيارات المستهدفة من Google و ChatGPT', label: 'متوسط نمو المبيعات العضوية' },
    strategy: { title: 'تحسين محركات البحث... هو آخر خطوة عندنا', hl: 'آخر خطوة',
      sub: 'لأن أولويتنا هي زيادة مبيعاتك، خطوات عملنا تبدأ من البيزنس وتنتهي بالتسويق.',
      steps: [
        ['تحليل السوق، والمنافسين، ونوايا الشراء', 'نبدأ بفهم السوق وتحليل الكلمات التي تعكس نية شراء حقيقية، والأسئلة التي يبحث عنها العميل قبل القرار.'],
        ['هندسة صفحات البيع ورفع معدلات التحويل', 'نحسن صفحات الهبوط لتكون مقنعة بصرياً ونصياً، فترتفع نسبة تحويل الزوار إلى مشترين.'],
        ['صناعة محتوى يبيع القيمة', 'محتوى يجيب على أسئلة العملاء ويعالج اعتراضاتهم، بدلاً من جذب زيارات غير مفيدة.'],
        ['التحسين لمحركات البحث والذكاء الاصطناعي', 'نحسن البنية التقنية وملاءمة الموقع لمعايير SEO وأنظمة الذكاء الاصطناعي لأقصى وصول عضوي.'],
        ['قياس الربحية.. وليس الترتيب', 'تقاريرنا تركز على ما يترجم إلى أرباح مثل ROAS، لا على مؤشرات الغرور كالترتيب أو حجم الزيارات.']] },
    partners: { title: 'شركاء النجاح', stories: 'قصص نجاح المتاجر', more: 'المزيد من قصص النجاح' },
    process: { title: 'كيف يتصدر موقعك النتائج الأولى على محركات البحث مع لينكاوي؟', hl: 'النتائج الأولى',
      sub: 'نتبع خطوات مدروسة لضمان تحسين ترتيب موقعك في محركات البحث وتحقيق نتائج ملموسة.', cta: 'ابدأ الآن',
      steps: [['الخطوة الأولى', 'نحلل موقعك لنكتشف فرص النمو', 'نراجع موقعك بالكامل، ونكتشف أين تضيع عليك الزيارات والفرص قبل منافسيك.'],
        ['الخطوة الثانية', 'نختار الكلمات التي تجذب عملاء حقيقيين', 'لا نطارد كلمات بلا قيمة، بل نستهدف ما يبحث عنه عملاؤك عندما يكونون مستعدين للشراء.'],
        ['الخطوة الثالثة', 'نبني استراتيجية سيو مصممة لك', 'خطة واضحة تشمل المحتوى والصفحات والبنية التقنية — بدون حلول جاهزة.'],
        ['الخطوة الرابعة', 'ننفّذ التحسينات ونحرّك النتائج', 'تنفيذ عملي خطوة بخطوة حتى يتحول موقعك إلى قناة جذب فعّالة.'],
        ['الخطوة الخامسة', 'نراقب الأداء ونحسّن باستمرار', 'نقيس النتائج ونعدّل الاستراتيجية باستمرار لضمان أفضل نمو ممكن.'],
        ['الخطوة السادسة', 'نتابع النتائج ونبني نموًا مستدامًا', 'تقارير واضحة وخطة طويلة المدى تضمن استمرار تفوّقك في نتائج البحث.']] },
    reasons: { title: '9 أسباب لاختيار لينكاوي', hl: '9 أسباب', highlight: 7,
      items: [['خبرة عابرة للقارات', 'أكثر من 10 أعوام من خدمات السيو في أسواق تنافسية مثل الإمارات والسعودية وأمريكا.'],
        ['الكلمات المفتاحية الأكثر ربحية', 'نستهدف العبارات التي تجلب لك عملاء وليس مجرد زيارات، لأعلى عائد على الاستثمار.'],
        ['نتائج موثقة في الظهور الرقمي', 'قصص نجاح في زيادة الزيارات العضوية لشركات كبرى والقفز إلى الصفحة الأولى.'],
        ['سيو تقني بالكامل', 'سرعة الموقع و Schema Markup وتجربة المستخدم لضمان الزحف والأرشفة بأفضل صورة.'],
        ['تقارير دورية وشفافية مطلقة', 'تقارير مفصلة وتواصل مباشر مع فريق العمل دون تعقيدات إدارية.'],
        ['مواكبة تحديثات الخوارزميات', 'نراقب خوارزميات Google باستمرار ونلتزم بـ White Hat SEO لحماية موقعك.'],
        ['روابط قوية واستراتيجية محتوى', 'بناء روابط من مواقع ذات سلطة عالية بالتوازي مع تسويق بالمحتوى يجعلك مرجعاً.'],
        ['استشارات مباشرة من المؤسس', 'تتعامل مع المهندس علي عطوة مباشرة، بقرارات مبنية على بيانات حقيقية.'],
        ['تدريب فريقك على السيو المستدام', 'ندرب فريقك على كتابة محتوى متوافق مع السيو والحفاظ على النتائج على المدى الطويل.']] },
    benefits: { title: 'نقود مشروعك نحو صدارة محركات البحث في 3 خطوات', hl: 'صدارة محركات البحث',
      items: [['فهم السوق والجمهور', 'نكتشف الفرص الأقوى ونحدد ما يبحث عنه عملاؤك المحتملون، لنبني أساساً يجعل الزيارات أكثر قيمة.', 'growth/seo-product-research.png'],
        ['خطة سيو واضحة الأهداف', 'لا نسعى إلى زيادة الأرقام شكليًا، بل نجذب زيارات مؤهلة تحمل نية شراء حقيقية.', 'growth/seo-marketing-plan.webp'],
        ['نتائج تنمو يومًا بعد يوم', 'السيو مسار نمو تراكمي؛ نحقق نمواً شهرياً مستمراً في الزيارات العضوية وفرص التحويل.', 'growth/sales-growth-dashboard.png']] },
    blog: { title: 'أحدث المقالات من المدونة', sub: 'نشارك معكم آخر التحديثات والاستراتيجيات في عالم تحسين محركات البحث.', all: 'تصفح كل المقالات', author: 'علي عطوة',
      posts: [['تحليلات', 'شرح جوجل أناليتكس: دليل شامل للمبتدئين', 'أي قرار تسويقي بدون قراءة سلوك الزوار قد يقودك إلى استنتاجات خاطئة.', '17 دقيقة قراءة', null],
        ['تحسين محركات البحث', 'قياس مؤشرات أداء الـ SEO في عصر الذكاء الاصطناعي', 'أهم مؤشرات أداء الـ SEO وكيف تربطها بأهدافك لنتائج ملموسة.', '13 دقيقة قراءة', 'https://www.linkawy.io/wp-content/uploads/Search-KPIs-400x209.png'],
        ['السيو الداخلي', 'تحسين عناوين URL موقعك لمحركات البحث', 'التفاصيل الصغيرة تصنع فارقاً كبيراً، وعناوين URL واحدة منها.', '9 دقائق قراءة', 'https://www.linkawy.io/wp-content/uploads/optimize-url-for-seo-400x211.png']] },
    founder: { eyebrow: 'أهلًا بالمؤسس', title: 'استشارات سيو برؤية بيزنس', hl: 'برؤية بيزنس',
      body: 'ندرك حجم الضغط الذي تواجهه كمؤسس وأنت ترى ميزانيتك تُستنزف في الإعلانات. صممنا هذه الاستشارات لتخرجك من مصيدة الدفع مقابل الظهور: تعمل مباشرة مع خبير سيو يمتلك رؤية بيزنس، بمنهجية نقلت شركات ناشئة من مجرد التواجد إلى الهيمنة عبر الزيارات المجانية.',
      cta: 'اطلب استشارة سيو', name: 'م. علي عطوة', role: 'مؤسس لينكاوي · 10+ سنوات في السيو' },
    faq: { title: 'الأسئلة الشائعة', sub: 'إجابات مباشرة عن الوقت والتكلفة والنتائج.', cta: 'تواصل معنا',
      items: [['ما هي خدمات SEO التي تقدمونها؟', 'السيو الداخلي والخارجي وبناء الروابط، السيو التقني، تحسين المحتوى، تحليل الكلمات المفتاحية، سيو المتاجر على شوبيفاي وسلة وزد، واستشارات السيو المتخصصة.'],
        ['كم من الوقت يستغرق تحسين ترتيب موقعي؟', 'السيو عملية تراكمية. تبدأ النتائج الملموسة عادةً خلال 3 إلى 6 أشهر وتتحسن باستمرار، حسب حالة الموقع والمنافسة وحجم العمل.'],
        ['هل تقدمون خدمات السيو للمتاجر الإلكترونية؟', 'نعم، نحن متخصصون في متاجر شوبيفاي وسلة وزد وووكومرس: صفحات المنتجات والتصنيفات والبنية التقنية.'],
        ['كيف يتم تحديد سعر خدمة السيو؟', 'حسب حجم الموقع، والمنافسة، والحالة التقنية، والأهداف، ونطاق العمل. نقدم عرض سعر مخصص بعد تحليل موقعك.'],
        ['هل يمكنكم ضمان المرتبة الأولى؟', 'لا يمكن لأي شركة سيو محترفة ضمان المرتبة الأولى، لكننا نضمن أفضل الممارسات ونمواً ملموساً في الترتيب والزيارات والمبيعات.'],
        ['كيف يتم قياس نجاح استراتيجية السيو؟', 'بنمو الزيارات العضوية، وتحسن ترتيب الكلمات المستهدفة، وزيادة التحويلات والمبيعات، والعائد على الاستثمار ROI.']] },
    results: { eyebrow: 'نتائج حقيقية', title: 'نتائج SEO', sub: 'شاهد النتائج من داخل الحسابات والمتاجر', cta: 'ابدأ قصة نجاحك الآن' },
    contact: { title: 'ابدأ رحلة تصدّر موقعك', sub: 'أخبرنا عن مشروعك وسنتواصل معك خلال 24 ساعة بخطة عمل مخصصة.',
      name: 'الاسم', email: 'البريد الإلكتروني', phone: 'رقم الهاتف', company: 'اسم الشركة', site: 'رابط الموقع', budget: 'الميزانية الشهرية', budgetPh: 'اختر الميزانية', goals: 'الأهداف والتحديات', send: 'إرسال الطلب',
      budgets: ['أقل من 750$', '750$ - 1,500$', '1,500$ - 3,000$', '3,000$ - 5,000$', '5,000$ - 10,000$', 'أكثر من 10,000$'],
      ok: 'تم إرسال طلبك بنجاح!', okSub: 'شكراً لتواصلك معنا. سنراجع طلبك ونتواصل معك خلال 24 ساعة بخطة عمل مخصصة.',
      perks: [['Clock', 'رد خلال 24 ساعة'], ['ClipboardCheck', 'تحليل مجاني لموقعك'], ['Users', 'تواصل مباشر مع المؤسس']] },
    footer: { ctaTitle: 'مستعد لتصدر نتائج البحث؟', ctaText: 'دعنا نستكشف الفرص معًا — سيحلل خبراؤنا موقعك ويقدمون خطة مخصصة لأهدافك.', ctaLabel: 'احجز استشارة مجانية',
      desc: 'شريكك الاستراتيجي في النمو الرقمي. نقدم حلول سيو وتصميم مواقع مبتكرة لضمان تصدرك النتائج.',
      cols: [['خدماتنا', ['شركة تسويق الكتروني', 'خدمات سيو', 'خدمات GEO / AI SEO', 'تصميم متاجر إلكترونية', 'خدمات باك لينك', 'شركة كتابة محتوى']],
        ['المصادر', ['المدونة', 'قاموس المصطلحات', 'شرح السيو للمبتدئين', 'مكتبة القوالب والأدوات', 'أوامر ومطالبات AI']],
        ['الشركة', ['من نحن', 'تواصل معنا', 'سياسة الخصوصية']]],
      contactTitle: 'اتصل بنا', location: 'الرياض، السعودية', email: 'info@linkawy.io', copyright: '© 2026 لينكاوي. جميع الحقوق محفوظة.' },
    ctaB: { title: 'مستعد لتصدر نتائج البحث؟', text: 'سيقوم خبراؤنا بتحليل موقعك وتقديم خطة مخصصة لتحقيق أهدافك.', label: 'احجز استشارة مجانية' },
    geo: { crumb: 'خدماتنا', title: 'سيو الذكاء الاصطناعي', accent: '(GEO)', sub: 'نهيّئ محتوى موقعك ليظهر ويُقتبس في محركات الإجابة: ChatGPT و Gemini و Perplexity و AI Overviews في Google.', primary: 'اطلب استشارة مجانية', secondary: 'شاهد النتائج',
      whatTitle: 'ماذا تشمل خدمة GEO؟', hl: 'GEO',
      what: [['Brain', 'فهم نوايا الأسئلة', 'نحدد الأسئلة التي يطرحها عملاؤك على أدوات الذكاء الاصطناعي قبل الشراء.'], ['FileText', 'محتوى قابل للاقتباس', 'إجابات واضحة ومنظمة وموثوقة تسهل على النماذج فهمها واقتباسها.'], ['Code', 'بيانات منظمة Schema', 'نعلّم صفحاتك ببيانات منظمة تربط علامتك بالكيانات والمنتجات.'], ['Radar', 'تتبع الظهور في الإجابات', 'نقيس ظهور علامتك في إجابات ChatGPT و Gemini ونحسّن باستمرار.']],
      stats: [['3x', 'ظهور أعلى في AI Overviews'], ['60%', 'من عمليات البحث تنتهي دون نقرة'], ['24h', 'للرد بخطة مبدئية']] },
    post: { crumb: 'المدونة', cat: 'تحسين محركات البحث', title: 'قياس مؤشرات أداء الـ SEO في عصر الذكاء الاصطناعي', meta: 'علي عطوة · 13 دقيقة قراءة · 29 أبريل 2026', toc: 'محتوى المقال',
      sections: [['لماذا تغيّرت مؤشرات الأداء؟', 'مع ظهور AI Overviews ومحركات الإجابة، لم تعد النقرات وحدها كافية لقياس نجاح السيو. أصبح الظهور داخل الإجابة نفسها مؤشراً مستقلاً يجب تتبعه.'],
        ['المؤشرات التي تترجم إلى أرباح', 'ركّز على الزيارات العضوية المؤهلة، ومعدل التحويل من البحث، والإيراد لكل زيارة، والعائد على الاستثمار. هذه الأرقام تخبرك إن كان السيو يبيع فعلاً.'],
        ['كيف تقيس الظهور في الذكاء الاصطناعي؟', 'راقب ذكر علامتك في إجابات ChatGPT و Gemini لأسئلة الشراء الأساسية، وتابع الزيارات القادمة من هذه المنصات في Google Analytics.']] },
  },
  en: {
    nav: { home: 'Home', services: 'Services', blog: 'Blog', resources: 'Resources', learn: 'Learn SEO', quote: 'Request a quote', lang: 'العربية',
      serviceItems: ['Digital marketing', 'Search engine optimization (SEO)', 'AI search optimization (GEO)', 'E-commerce store design', 'Backlink services', 'Content writing'] },
    hero: { label: 'Now optimizing stores for ChatGPT & Gemini answers', badge: 'NEW', pre: 'The SEO agency for ', accent: 'e-commerce stores', post: ' and companies',
      sub: "Choosing the right SEO agency isn't just about rankings — it's building a growth channel that connects search to sales. Our strategies put you at the top of results and bring qualified traffic that turns into lasting revenue.",
      primary: 'Discover services', secondary: 'How we work', clients: "Clients we've had the honor to help:",
      platforms: [['google', 'Result #1', 'Google SERP'], ['gemini', 'AI Overview', 'Gemini'], ['chatgpt', 'LLMO / GEO', 'ChatGPT'], ['semrush', 'DR 80 +3', 'Authority Score'], ['googlemaps', 'Maps ranking', 'Local SEO'], ['applenews', 'Media coverage', 'Digital PR']],
      platformsTitle: 'An SEO agency that turns traffic into real profit, on every platform' },
    services: { eyebrow: 'Our services', title: 'The SEO services we deliver', hl: 'SEO services',
      sub: 'Custom strategies with the guidance and support to help you top search results and grow with confidence.', cta: 'Book a free consultation',
      items: [
        ['ShoppingBag', 'Shopify SEO', 'Shopify', 'Pages, products and content structure tuned for search, so your Shopify store is found by more of the right buyers.'],
        ['Store', 'Salla SEO', 'Salla', 'Pages, categories, products and internal content for Salla stores — more organic visits, more sales.'],
        ['FileText', 'On-page SEO', 'On-page', 'Titles, content, internal links and page structure, so search engines understand every page.'],
        ['Link', 'Off-page SEO', 'Off-page', 'High-quality backlinks from trusted, relevant sites that lift your authority and rankings.'],
        ['ScanSearch', 'SEO audits', 'Audits', 'A full audit of technical, speed, indexing and content issues — with practical fixes, in order.'],
        ['Lightbulb', 'SEO consulting', 'Consulting', 'A clear view and sharp priorities for your stage — whether you start from zero or scale results.'],
        ['Code', 'Technical SEO', 'Technical', 'Speed, mobile, security and URL structure, so your site is easy to crawl and index.'],
        ['Sparkles', 'AI search SEO', 'GEO', 'Clear, trusted, structured content that answer engines and AI search can understand and cite.']] },
    proof: { pre: 'On average we grew our clients’ organic sales by more than ', num: '270%', post: ' through targeted traffic from Google and ChatGPT', label: 'Average organic sales growth' },
    strategy: { title: 'Search engine optimization is our last step', hl: 'last step',
      sub: 'Our priority is growing your sales, so our work starts with the business and ends with marketing.',
      steps: [
        ['Market, competitor and buying-intent analysis', 'We start by understanding the market, the keywords with real buying intent and the questions buyers ask before they decide.'],
        ['Sales-page engineering and conversion lift', 'We make landing pages persuasive in copy and design, so more visitors become buyers.'],
        ['Content that sells the value', 'Content that answers buyers’ questions and handles objections — not traffic that goes nowhere.'],
        ['Optimization for search and AI', 'Technical structure tuned for SEO standards and modern AI systems, for maximum organic reach.'],
        ['Measuring profit, not rankings', 'Our reports track what turns into profit, like ROAS — not vanity metrics like rank or raw traffic.']] },
    partners: { title: 'Success partners', stories: 'Store success stories', more: 'More success stories' },
    process: { title: 'How Linkawy gets your site to the first results', hl: 'first results',
      sub: 'A deliberate set of steps to lift your rankings and deliver results you can measure.', cta: 'Start now',
      steps: [['Step one', 'We analyze your site to find growth', 'A full review of your site to find where traffic and opportunities leak to competitors.'],
        ['Step two', 'We pick keywords that bring real buyers', 'No chasing empty keywords — we target what your buyers search when they are ready to act.'],
        ['Step three', 'We build an SEO strategy made for you', 'A clear plan for content, pages and technical structure — no off-the-shelf fixes.'],
        ['Step four', 'We ship improvements and move results', 'Hands-on execution, step by step, until your site becomes a real acquisition channel.'],
        ['Step five', 'We monitor and keep improving', 'We measure, review and adjust the strategy continuously for the best possible growth.'],
        ['Step six', 'We follow through and build lasting growth', 'Clear reports and a long-term plan that keeps you ahead in search.']] },
    reasons: { title: '9 reasons to choose Linkawy', hl: '9 reasons', highlight: 7,
      items: [['Cross-continental expertise', '10+ years of SEO in competitive markets like the UAE, Saudi Arabia and the US.'],
        ['The most profitable keywords', 'We target phrases that bring customers, not just visits — for the highest return.'],
        ['Documented visibility results', 'Success stories growing organic traffic for major companies and reaching page one.'],
        ['Complete technical SEO', 'Speed, schema markup and UX, so crawlers index your pages in the best shape.'],
        ['Regular reports, full transparency', 'Detailed reports and direct contact with the team — no admin layers.'],
        ['On top of algorithm updates', 'We watch Google’s algorithms closely and stay strictly white-hat.'],
        ['Strong backlinks and content', 'Links from high-authority sites alongside content that makes you the reference.'],
        ['Direct consulting with the founder', 'You work with Eng. Ali Atwa directly, on decisions backed by real data.'],
        ['Training your team', 'We train your team on SEO-ready content so results last for the long term.']] },
    benefits: { title: 'We lead your project to the top of search in 3 steps', hl: 'top of search',
      items: [['Understand the market and audience', 'We find the strongest opportunities and what your buyers search for, so every visit is worth more.', 'growth/seo-product-research.png'],
        ['An SEO plan with clear goals', 'We don’t inflate numbers. We bring qualified visits with real intent to buy.', 'growth/seo-marketing-plan.webp'],
        ['Results that grow every day', 'SEO compounds. We deliver steady monthly growth in organic traffic and conversions.', 'growth/sales-growth-dashboard.png']] },
    blog: { title: 'Latest from the blog', sub: 'The latest updates and strategies from the world of search.', all: 'Browse all articles', author: 'Ali Atwa',
      posts: [['Analytics', 'Google Analytics explained: a complete beginner’s guide', 'Any marketing decision made without reading visitor behavior can lead you to the wrong conclusions.', '17 min read', null],
        ['SEO', 'Measuring SEO KPIs in the age of AI', 'The SEO KPIs that matter and how to tie them to your goals for tangible results.', '13 min read', 'https://www.linkawy.io/wp-content/uploads/Search-KPIs-400x209.png'],
        ['On-page SEO', 'Optimizing your URLs for search engines', 'In SEO, small details make a big difference — and URLs are one of them.', '9 min read', 'https://www.linkawy.io/wp-content/uploads/optimize-url-for-seo-400x211.png']] },
    founder: { eyebrow: 'Hello, founder', title: 'SEO consulting with a business lens', hl: 'business lens',
      body: 'We know the pressure of watching your budget drain into ads. These consultations get you out of the pay-to-be-seen trap: you work directly with an SEO expert who thinks in business terms, using a method that has taken startups from simply existing to dominating through free traffic.',
      cta: 'Request SEO consulting', name: 'Eng. Ali Atwa', role: 'Founder, Linkawy · 10+ years in SEO' },
    faq: { title: 'Frequently asked questions', sub: 'Straight answers on timelines, pricing and results.', cta: 'Contact us',
      items: [['What SEO services do you offer?', 'On-page and off-page SEO, link building, technical SEO, content optimization, keyword research, store SEO on Shopify, Salla and Zid, and specialist consulting.'],
        ['How long does it take to improve my rankings?', 'SEO compounds. Tangible results usually show within 3 to 6 months and keep improving, depending on your site, competition and scope.'],
        ['Do you work with e-commerce stores?', 'Yes — we specialize in Shopify, Salla, Zid and WooCommerce: product pages, categories and technical structure.'],
        ['How is SEO pricing decided?', 'By site size, competition, technical state, goals and scope. We send a custom quote after analyzing your site.'],
        ['Can you guarantee the #1 position?', 'No honest SEO agency can. We guarantee best practice and measurable growth in rankings, traffic and sales.'],
        ['How do you measure SEO success?', 'Organic traffic growth, target-keyword rankings, conversions and sales, and return on investment.']] },
    results: { eyebrow: 'LIVE RESULTS', title: 'SEO results', sub: 'Straight from inside client accounts and stores', cta: 'Start your success story' },
    contact: { title: 'Start your climb to the top', sub: 'Tell us about your project and we’ll reply within 24 hours with a custom plan.',
      name: 'Name', email: 'Email', phone: 'Phone', company: 'Company', site: 'Website', budget: 'Monthly budget', budgetPh: 'Select a range', goals: 'Goals & challenges', send: 'Send request',
      budgets: ['Under $750', '$750 – $1,500', '$1,500 – $3,000', '$3,000 – $5,000', '$5,000 – $10,000', 'Over $10,000'],
      ok: 'Your request is in!', okSub: 'Thanks for reaching out. We’ll review it and reply within 24 hours with a custom plan.',
      perks: [['Clock', 'Reply within 24 hours'], ['ClipboardCheck', 'Free site analysis'], ['Users', 'Direct line to the founder']] },
    footer: { ctaTitle: 'Ready to top the search results?', ctaText: 'Let’s explore the opportunities together — our experts will analyze your site and send a custom plan.', ctaLabel: 'Book a free consultation',
      desc: 'Your strategic partner in digital growth — SEO and store design built to rank.',
      cols: [['Services', ['Digital marketing', 'SEO services', 'GEO / AI SEO', 'Store design', 'Backlinks', 'Content writing']],
        ['Resources', ['Blog', 'SEO glossary', 'Learn SEO', 'Templates & tools', 'AI prompts']],
        ['Company', ['About', 'Contact', 'Privacy policy']]],
      contactTitle: 'Contact', location: 'Riyadh, Saudi Arabia', email: 'info@linkawy.io', copyright: '© 2026 Linkawy. All rights reserved.' },
    ctaB: { title: 'Ready to top the search results?', text: 'Our experts will analyze your site and send a custom plan for your goals.', label: 'Book a free consultation' },
    geo: { crumb: 'Services', title: 'AI search optimization', accent: '(GEO)', sub: 'We shape your content to be found and cited by answer engines: ChatGPT, Gemini, Perplexity and Google AI Overviews.', primary: 'Book a free consultation', secondary: 'See results',
      whatTitle: 'What GEO covers', hl: 'GEO',
      what: [['Brain', 'Question intent', 'We map the questions your buyers ask AI tools before they buy.'], ['FileText', 'Citable content', 'Clear, structured, trustworthy answers that models understand and quote.'], ['Code', 'Structured data', 'Schema that ties your brand to entities and products.'], ['Radar', 'Answer tracking', 'We track your brand in ChatGPT and Gemini answers and keep improving.']],
      stats: [['3x', 'More AI Overview visibility'], ['60%', 'Of searches end without a click'], ['24h', 'To your first plan']] },
    post: { crumb: 'Blog', cat: 'SEO', title: 'Measuring SEO KPIs in the age of AI', meta: 'Ali Atwa · 13 min read · Apr 29, 2026', toc: 'In this article',
      sections: [['Why KPIs changed', 'With AI Overviews and answer engines, clicks alone no longer measure SEO success. Visibility inside the answer itself is now a metric of its own.'],
        ['The metrics that turn into profit', 'Focus on qualified organic traffic, search conversion rate, revenue per visit and ROI. These tell you whether SEO actually sells.'],
        ['How to measure AI visibility', 'Track brand mentions in ChatGPT and Gemini answers for your core buying questions, and the traffic those platforms send in Google Analytics.']] },
  },
};
